// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWkbwqditHzoucy9SGAEGqscuZ31rFRcM',
    appId: '1:902895010395:web:5f344ca68b1b3fd7c2757e',
    messagingSenderId: '902895010395',
    projectId: 'notifier-1be62',
    authDomain: 'notifier-1be62.firebaseapp.com',
    databaseURL: 'https://notifier-1be62-default-rtdb.firebaseio.com',
    storageBucket: 'notifier-1be62.appspot.com',
    measurementId: 'G-JM2N2CZ6ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA36L4eKy0XI4JteSOidEVOuNPGJlF1VhQ',
    appId: '1:902895010395:android:4cdc898b1791e5d8c2757e',
    messagingSenderId: '902895010395',
    projectId: 'notifier-1be62',
    databaseURL: 'https://notifier-1be62-default-rtdb.firebaseio.com',
    storageBucket: 'notifier-1be62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmqbnXddfXVsF41y_JQKzmgEWIYFT0o1s',
    appId: '1:902895010395:ios:a6571358e08f1d4cc2757e',
    messagingSenderId: '902895010395',
    projectId: 'notifier-1be62',
    databaseURL: 'https://notifier-1be62-default-rtdb.firebaseio.com',
    storageBucket: 'notifier-1be62.appspot.com',
    androidClientId: '902895010395-1dj3v4o6f5vobfj7kbd87bj3bm3vkrvh.apps.googleusercontent.com',
    iosClientId: '902895010395-bd5rgfkcb59fbi3e3qcj2c73nc4co3eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.icalMabite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmqbnXddfXVsF41y_JQKzmgEWIYFT0o1s',
    appId: '1:902895010395:ios:4465f27209e80692c2757e',
    messagingSenderId: '902895010395',
    projectId: 'notifier-1be62',
    databaseURL: 'https://notifier-1be62-default-rtdb.firebaseio.com',
    storageBucket: 'notifier-1be62.appspot.com',
    androidClientId: '902895010395-1dj3v4o6f5vobfj7kbd87bj3bm3vkrvh.apps.googleusercontent.com',
    iosClientId: '902895010395-9ftujfibv20otl7nn3qcv63csguuu9f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.icalMabite.RunnerTests',
  );
}
